[[edge_functions]]
  path = "/*/testimony/*"
  function = "share"

[[edge_functions]]
  path = "/*/dhyanam/*"
  function = "share"

[[edge_functions]]
  path = "/*/oracles/*"
  function = "share"

[[edge_functions]]
  path = "/*/prayers/*"
  function = "share"